- kernel/interrupts.c
- kernel/time.c
Initial implementation of sleep using the new INTR_TIMER interrupts from ukvm. The issue with implementing a "pv" sleep is that ocaml sleep only needs a clock and implements the actual sleeping/blocking itself.
> clock based on ukvm INTR_TIMER interrupts

- .gitignore
.gitignore should include mirage.mk as it is autogenerated.
> gitignore should include mirage.mk

- ukvm/ukvm.c
Not strictly required as the mmap()ed guest memory block should be
initialised to all zeroes, but we don't want to rely on that.
> Initialise BOOT_PDPTE to zero

- ukvm/processor-flags.h
- ukvm/ukvm.c
Not all processors support 1GB pages, so switch to 2MB pages in guest
as the next-simplest solution for now. Should address #6.
> ukvm: Switch to 2MB page size in guest

- Makefile
- kernel/Makefile
- kernel/ee_printf.c
- kernel/kernel.h
- kernel/malloc.c
- kernel/solo5.h
- kernel/stubs.c
- kernel/test_hello.c
- kernel/test_ping_serve.c
- kernel/time.c
- kernel/ukvm/io.c
- kernel/ukvm/low_level.c
- kernel/ukvm/low_level_interrupts.c
- kernel/ukvm/time.c
- kernel/virtio/kernel.c
- kernel/virtio/low_level.c
- kernel/virtio/low_level_interrupts.c
- kernel/virtio/net.c
- kernel/virtio/time.c
- kernel/virtio/virtio.c
- solo5-kernel-ukvm.opam
- solo5-kernel-ukvm.pc.in
- solo5-kernel-virtio.opam
- solo5-kernel-virtio.pc.in
Part of djwillia/solo5#19, djwillia/solo5#23. To be applied concurrently with forthcoming PRs to djwillia/mirage, djwillia/mirage-platform.
> Namespace solo5 APIs, migrate to ocaml-freestanding runtime

- ukvm/ukvm.c
The x86_64 ABI mandates that (%rsp + 8) be a multiple of 16 on entry to
a user function. GCC relies on this when using SSE instructions and will
ensure correct alignment is preserved in subsequent function calls.
Per testing, virtio target already appears (possibly not intentionally)
to have the correct stack alignment.
> Fix stack alignment for ukvm target

- kernel/kernel.h
- kernel/solo5.h
- kernel/time.c
- kernel/ukvm/time.c
- kernel/virtio/time.c
- kernel/virtio/virtio.c
- ukvm/ukvm.c
- ukvm/ukvm.h
- solo5_poll API to block and wait for I/O. Replaces solo5_cpu_block().
- UKVM_PORT_POLL hypercall to implement solo5_poll() for ukvm target.
> Add solo5_poll(), UKVM_PORT_POLL

- kernel/virtio/low_level_interrupts.c
- kernel/virtio/pci.c
This is a temporary hack to "fix" #32 so that I don't have to keep
carrying a patch in my local tree.
> Handle both IRQ10 and IRQ11 via handle_virtio_interrupt()

- kernel/test_hello.c
- kernel/test_ping_serve.c
- kernel/ukvm/kernel.c
- kernel/virtio/kernel.c
- ukvm/Makefile
- ukvm/ukvm.c
- ukvm/ukvm.h
- Command line arguments are passed as a single string to
start_kernel(). To be consistent across ukvm/virtio, we pass only the
arguments and strip any "kernel name" supplied by the bootloader.
- ukvm: Define a ukvm_boot_info structure and pass this to kernel_main()
instead of individual arguments.
- ukvm: Rationalize memory map and update comments to reflect the
changes.
- ukvm: Look for '--gdb' before kernel arguments.
- The command line length limits for ukvm (~56k) and virtio (8k) are
arbitrary, however we warn if the command line is truncated.
> Pass command line arguments to the unikernel/application

- kernel/solo5.h
- kernel/test_hello.c
- kernel/test_ping_serve.c
- kernel/ukvm/kernel.c
- kernel/virtio/kernel.c
Better naming for the application entrypoint. Also, move prototype to
solo5.h to ensure consistency.
> Rename start_kernel() to solo5_app_main()

- README.md
- checkpatch.pl
- kernel/ee_printf.c
- kernel/interrupts.c
- kernel/interrupts.h
- kernel/kernel.h
- kernel/lib.c
- kernel/stubs.c
- kernel/test_hello.c
- kernel/test_ping_serve.c
- kernel/ukvm/gdt.c
- kernel/ukvm/io.c
- kernel/ukvm/kernel.c
- kernel/ukvm/low_level.c
- kernel/ukvm/low_level_interrupts.c
- kernel/ukvm/mem.c
- kernel/ukvm/time.c
- kernel/virtio/kernel.c
- kernel/virtio/low_level.c
- kernel/virtio/low_level_interrupts.c
- kernel/virtio/mem.c
- kernel/virtio/net.c
- kernel/virtio/pci.c
- kernel/virtio/serial.c
- kernel/virtio/time.c
- kernel/virtio/virtio.c
- ukvm/gdb-stub.c
- ukvm/ukvm.c
- ukvm/ukvm.h
This should address most of the style for the .c and .h files.  For the most part I did not change files that were direct copies from other projects (e.g., `malloc`, clock code, etc.)  No functional changes are expected. 
I also checked in `checkpatch.pl` from Linux with the leading tab checks and a few other Linux specific checks commented out.  It doesn't catch everything and there are a few things (`extern`s mostly) that are still being warned about, but it should give us a good first pass for style checks.
> set style to "Linux style but with 4 spaces instead of tabs"

- kernel/Makefile
- kernel/ukvm/solo5.lds
- kernel/virtio/solo5.lds
- switch to --nmagic instead of -z max-page-size, the latter doesn't
work on FreeBSD (thanks @hannesm for reporting and investigation)
- clean up linker scripts for both virtio and ukvm targets
> Fix linker scripts

- kernel/Makefile
this is (imho) less brittle...
> use -print-file-name=include instead of -print-search-dirs and sed magic

- kernel/virtio/virtio.c
virtio/virtio.c:240:49: error: missing field 'gso_type' initializer
[-Werror,-Wmissing-field-initializers]
static struct virtio_net_hdr virtio_net_hdr = {0};
> fix C warning (clang 3.8.1)

- kernel/Makefile
- kernel/ukvm/solo5.lds
- kernel/virtio/solo5.lds
--nmagic has side effects which a) break ukvm and b) we don't want in general (results in a single RWX phdr for the entire kernel). Revert those changes, and introduce a possible workaround for FreeBSD.
> Revert changes to linker scripts / --nmagic

- kernel/Makefile
- ukvm/Makefile
at least on all the machines I have access to, even on ubuntu linux, you get a cc binary... cc is also common on MacOSX and FreeBSD for the C compiler... (where there might be no gcc installed)...
> CC is cc, not gcc

- kernel/malloc.c
- kernel/ukvm/mem.c
- kernel/virtio/mem.c
- simplify sbrk() code path
- page alignment is not required in sbrk()
- enable giving back memory via sbrk() and tell malloc() about it
- don't abort in malloc() if memory exhausted, instead return NULL which
should trigger OCaml GC
Related to #58, although does not fundamentally affect the issue.
> malloc() and sbrk() fixes

- kernel/ukvm/time.c
- ukvm/ukvm.c
- ukvm/ukvm.h
If solo5_poll() on ukvm is called after until_nsecs have passed then we
pass a negative value to UKVM_PORT_POLL which results in waiting for a
very long time.
Also clarify the UKVM_PORT_POLL interface to make it clear that the
timeout is relative, not absolute.
> ukvm: Fix overflow if solo5_poll() called too late

- Makefile
- ukvm/Makefile
- ukvm/Makefile.ukvm
- ukvm/ukvm-blk.c
- ukvm/ukvm-gdb.c
- ukvm/ukvm-net.c
- ukvm/ukvm.c
- ukvm/ukvm_config.bash
- ukvm/ukvm_modules.h
This breaks ukvm into a few different modules.  The idea is that it can be built without one or more of the modules, and I'd like to eventually make OPAM know about how to build a monitor for a unikernel based on what it needs.  For the first commit, I'm checking in a ukvm build config (`Makefile.ukvm`) which includes all modules, so functionally everything should stay the same.
This is a bit of an annoying change for a few reasons:
- it moves a bunch of code into different files
- it changes the argument order to `ukvm` yet again (see issue #26 )
This also bumps up on a few things that are changing or will change
- it only supports one instance of each type of device (e.g., net, disk)
- the `poll` code now gets its fd list from the modules (still only net at the moment)
> modularize ukvm

- .gitignore
- Makefile
- solo5-kernel-ukvm.opam
- solo5-kernel-virtio.opam
- tests/Makefile
- tests/Makefile.tests
In #64 the tests are split out into their own subdirectories, however it
is no longer possible to build only for ukvm or virtio. As the ukvm
target is Linux-specific, this is not ideal.
Summary of changes:
- Allow independent build of ukvm or virtio. The default make target is
still "everything".
- Rename top-level targets to just "ukvm" and "virtio", to be consistent
with sub-Makefiles.
- Ensure that the tests are always built. This is important since now
the ukvm binary is no longer built at Solo5 build time but rather
at unikernel build time (#64) we need to be sure that all components
build correctly at any given point.
- The rest is just cosmetics and cleanups, removal of unused top-level
Makefile targets and fixes for parallel make.
> Fully independent virtio and ukvm build

- ukvm/ukvm-configure
- Fails to build on alpine due to busybox readlink not supporting '-e'.
- Add extra error checks to ensure UKVM_SRC looks like a ukvm source
directory.
> ukvm-configure fixes

- tests/Makefile.tests
the `test_hello` defines both UKVM_TARGETS and VIRTIO_TARGETS, but there's no Makefile.ukvm generated when virtio tests are run: ignore failing to load it (and provide a phony ukvm-clean)
> fix make virtio and make clean

- README.md
Now that support for Solo5 targets is merged into MirageOS, update the README to direct people to use the mirage-dev repository instead of solo5/opam-solo5.
> Update README to use mirage-dev repository

- kernel/Makefile
- kernel/ukvm/kernel.c
- kernel/ukvm/solo5.lds
- kernel/virtio/boot.S
- kernel/virtio/solo5.lds
Summary of changes:
- New, unified, linker scripts for ukvm and virtio. Addresses #73.
- Mainly cosmetic changes to link order and bootstrap stack placement. Makes eyeballing the symbol table for correctness easier.
> Memory layout fixes

- tests/Makefile
- tests/test_blk/Makefile
- tests/test_blk/test_blk.c
This is a small test for the solo5 blk IO interface. It just writes some sectors and checks that the read content matches.
```
./ukvm-bin --disk=/home/opam/disk.img ./test_blk.ukvm
qemu-system-x86_64 -s -nographic -name foo -m 1024 -kernel test_blk.virtio -device virtio-net,netdev=n0 -netdev tap,id=n0,ifname=tap100,script=no,downscript=no -drive file=/home/opam/disk.img,if=virtio
```
> Adding a blk test kernel for the solo5 interface

- kernel/virtio/virtio.c
for (i = 0; i > 2; i++) will never be executed, intension is to run it twice
> VIRTIO_PCI_QUEUE_PFN is a 32bit register

- ukvm/ukvm-configure
Allows building `ukvm-bin` statically.
> Add a UKVM_STATIC=1 option to generated Makefile.ukvm

- kernel/virtio/virtio.c
Changes:
1. the max queue size for rx and tx is now 4096 and the final value is not hardcoded.
2. the receive operation now gets one buffer descriptor at a time, instead of two (it was too complicated to have 2).
3. adds some asserts in some places to "assert" our assumptions.
Tested the mir-stackv4 and mirage static-website unikernels in:
1. qemu 2.1.2 on linux (with dhcp and without)
2. Google compute engine (with dhcp=true)
3. qemu 2.6 with this patch to increase the size of the queues (GCE must have this patch or something similar): https://lists.gnu.org/archive/html/qemu-devel/2015-11/msg06194.html
> virtio: Increase max queue size, use single descriptor for RX/TX

- kernel/Makefile
- kernel/interrupts.c
- kernel/kernel.h
- kernel/pvclock.c
- kernel/virtio/pci.c
- kernel/virtio/virtio.c
- tests/test_ping_serve/Makefile
- tests/test_ping_serve/test_ping_serve.c
Rather than fighting the toolchain to understand why globals are getting allocated as COMMON, I've changed all global variables to `static`.
~~A casualty of this process is `test_ping_serve`, since that was relying on poking around in variables declared in `virtio.c`.~~
~~@djwillia @ricarkol Please confirm you're ok with removing `test_ping_serve` -- I think we discussed this and concluded it's not worth keeping in it's current form?~~
> Kill all global variables

- kernel/virtio/low_level_interrupts.c
Bhyve assigns irq 5 to the virtio device, so add another workaround
until #32 is fixed.
> virtio: Handle irq 5.

- kernel/virtio/virtio.c
- kernel/virtio/virtio_ring.h
All Virtio's vring related structs are defined in an attached `.h` file in the virtio documentation: http://docs.oasis-open.org/virtio/virtio/v1.0/csprd01/virtio-v1.0-csprd01.html "7 virtio_ring.h". This change adds that file and changes virtio.c to use those definitions instead.
@mato @djwillia
> Use virtio ring definitions from virtio_ring.h

- kernel/interrupts.c
- kernel/virtio/virtio.c
- Fix IST1 stack placement
- Don't attempt to run interrupt handler for non-existent device
- Fail on solo5 I/O calls to non-existent device
> virtio: Interrupt handling fixes

- ukvm/ukvm-core.c
Since ukvm expects its payload to be in ELF format, validate that the ELF header has expected magic characters. Without the validation, any image format (ex: qcow2, which is the default OSv image format) is loaded successfully, and ``vcpu_loop`` execution fails with ``KVM_EXIT_SHUTDOWN`` ([Issue 13](https://github.com/Solo5/solo5/issues/88)).
This PR attempts to validate ELF magic characters in the loaded code so that -
a) user is informed of mismatched image format
b) ukvm does not attempt to get into ``vcpu_loop`` with a corrupt guest
___________
Testing Done:
Invalid image without validation:
```
root@ubuntu:~/solo5/tests/test_hello# ./ukvm-bin /tmp/osv-images/ukvm.img 
Setting the CPUID.
ukvm-bin: exit_reason = 0x8
root@ubuntu:~/solo5/tests/test_hello# 
```
Invalid image with ELF …
> Validate image passed to ukvm is in ELF format

- kernel/Makefile
- kernel/virtio/virtio_blk.c
- kernel/virtio/virtio_net.c
- kernel/virtio/virtio_ring.c
- kernel/virtio/virtio_ring.h
- tests/test_blk/test_blk.c
This PR is for two changes:
1. The network header in bhyve's virtio-net implementation is hard coded to use the extra `num_buffers` field (or `vrh_bufs` in freebsd code) even when the `VIRTIO_NET_F_MRG_RXBUF` feature is not negotiated. This proposed change uses the extended network header, asserts the host feature `VIRTIO_NET_F_MRG_RXBUF`, and negotiates it with the host (always). Here is the freebsd code with the hardcoded struct for reference: https://github.com/freebsd/freebsd/blob/master/usr.sbin/bhyve/pci_virtio_net.c#L120
2. The Tx path in bhyve's virtio-net assumes that all Tx'es will have a first descriptor with the header alone. Here is the code. https://github.com/freebsd/freebsd/blob/master/usr.sbin/bhyve/pci_virtio_net.c#L617 has an interesting comment, and …
> virtio: Refactoring and cleanup

- kernel/virtio/virtio_blk.c
- kernel/virtio/virtio_net.c
- kernel/virtio/virtio_ring.c
- kernel/virtio/virtio_ring.h
- tests/test_ping_serve/test_ping_serve.c
This change removes all the interrupt handling code from virtio-net and virtio-blk. It's mainly done for simplicity purposes. We can do this at the moment because our IO calls are synchronous, and we poll for receiving network packets anyway. Nothing was previously done on interrupt handling besides advancing our index of used descriptors (i.e. last_used). To know that the device used a descriptor (e.g. it put a packet on the ring), we can just check the ring's used->idx index that gets incremented by the device whenever it uses a descriptor chain.
Tests:
- test_ping_serve and test_blk locally on kvm
- static_website on GCE
Quick perf test (`ping -f` against test_ping_serve on kvm):
- current master: `round-trip min/avg/max/stddev = 0.094/0.285/2.296/0.111 ms`
- after change: `round-trip …
> Getting rid of virtio interrupt handling

- kernel/ukvm/kernel.c
- kernel/ukvm/mem.c
- kernel/virtio/mem.c
This is useful to be able to quickly eyeball that the memory layout
looks sane and will also aid in debugging addresses in traps / other
crashes.
STACK_GUARD_SIZE is a primitive way of ensuring that (at least) heap
allocation does not overflow into the stack. Ideally we'd want to check
the converse also (stack does not overflow into heap) but the
infrastructure for that is not there yet.
> Print memory map on boot, add stack guard space

- kernel/abort.c
- kernel/exit.c
- kernel/intr.c
- kernel/kernel.h
- kernel/pvclock.c
- kernel/ukvm/kernel.c
- kernel/virtio/kernel.c
- kernel/virtio/kernel.h
- kernel/virtio/pci.c
- kernel/virtio/platform.c
- kernel/virtio/tscclock.c
- kernel/virtio/virtio_blk.c
- kernel/virtio/virtio_net.c
- kernel/virtio/virtio_ring.c
- Prefix all messages with 'Solo5 ', allowing for easy eyeballing of
"who printed what" in logs.
- Print more / structured information during PCI enumeration and config.
- No functional change intended, but I had to revamp the data structures
passed around in the PCI code, mostly to get the bus/dev numbers out.
> Prefix all messages with 'Solo5: '

- kernel/virtio/virtio_net.c
- tests/test_ping_serve/test_ping_serve.c
There was an issue in the checksum function in test_ping_serve, where many packets had incorrect checksums and were reported by `ping -f` as missed.
Other changes are:
1. reverse the quiet/verbose behavior of test_ping_serve, now any arg passed means verbose mode.
2. there was an assert in virtio_net.c that can legitimately fail when the 16 bit indexes wrap over.
> Test ping serve fix checksum

- Makefile
- README.md
- tests/test_hello/test_hello.c
- tools/run/solo5-run-virtio.sh
Intended for development, testing and CI, not as a general tool for
launching unikernels. Supports kvm, qemu and bhyve.
> Add 'solo5-run-virtio' tool for launching virtio tests

- kernel/abort.c
- kernel/virtio/platform.c
- tools/run/solo5-run-virtio.sh
This is a hack, but it's the cleanest hack I could find that does the
job without doing anything which could be considered destructive on
other hypervisors.
> Use qemu "isa-debug-exit" device to shutdown on virtio

- kernel/virtio/virtio_blk.c
- tests/test_blk/test_blk.c
This PR is for two issues:
- `test_blk` is using `solo5_blk_*_sync` incorrectly, as these use sector numbers and not byte offsets.
- `virtio_blk_op` is not cleaning up the IO bufs completely before reusing them. The consequence is that IO bufs can reuse the flags of previous IOs, which happens when wrapping over the ring.
> test-blk is using byte offsets and virtio_blk not cleaning up IO bufs before using them

- ukvm/ukvm-blk.c
- ukvm/ukvm-core.c
- ukvm/ukvm-gdb.c
- ukvm/ukvm-modules.h
- ukvm/ukvm-net.c
- Ensure all error messages go to stderr.
- Consistently use err()/errx()/warn()/warnx() everywhere.
- Slightly less terse error messages for users.
- Cosmetic cleanups for usage errors.
- Remove some more commented out/debug code.
- Remove "useless" success messages (CPUID, blk/net setup).
No functional change intended with the exception of the last point (silent operation).
@djwillia I think this addresses "ukvm host feature detection" in #82. #9 talks about a few other things:
- TSC stability: that's a guest issue, I may add some detection to Solo5 for this if needed
- guest page size support which is moot for the moment since 2MB pages are supported on all x86_64 processors)
> ukvm: Clean up error messages

- .travis.yml
- README.md
- tests/README.md
- tests/run-tests.sh
- tests/setup-tests.sh
- tests/test_blk/test_blk.c
- tests/test_hello/test_hello.c
- tests/test_ping_serve/test_ping_serve.c
- tools/run/solo5-run-virtio.sh
TL;DR: `sudo tests/setup-tests.sh && sudo tests/run-tests.sh`.
Finally, a test suite that runs end to end tests using the standalone test programs in `tests/`. See tests/README.md for usage.
The test harness is a rather gnarly shell script, this is the simplest I could get to that has the basic functionality we need. There are more interesting things that can be done with automated tests, but those will probably need a test harness written in something better than shell.
Please review. 
@hannesm There is a race condition _somewhere_ in the innards of `solo5-run-virtio.sh` for Bhyve which may cause random hard hangs (not sure why `timeout` is not doing the right thing in this case). Will debug in due course.
Part of #82, (1) "end to end CI".
> Add a test suite

- ukvm/ukvm-private.h
GUEST_CHECK_PADDR relies on the incorrect assumption that (uint64_t) is the same type as (unsigned long) and uses __builtin_uaddl_overflow() for checked arithmetic. This does not hold for all compiler configurations.
> Make no assumptions about type of uint64_t in GUEST_CHECK_PADDR 

- Makefile
- tests/Makefile.tests
- ukvm/ukvm-configure
1. Make _build_ukvm/ an order-only prerequisite, thus not rebuilding
bits of ukvm every time due to the timestamp on the directory changing.
2. Add $(MAKEFILE_LIST) to ukvm dependencies, forcing a rebuild of ukvm
if the generated Makefile has changed (e.g. from re-running of
ukvm-configure).
> ukvm-configure: Correct dependencies in generated Makefile

- ukvm/ukvm-core.c
Check that total amount to be read is <= SSIZE_MAX.
> ukvm: Check limits in pread_in_full()

- kernel/virtio/virtio_blk.c
- tests/test_blk/test_blk.c
- ukvm/ukvm-blk.c
- ukvm-blk: guard against read/write beyond "end of device"
- ukvm-blk: switch to pread()/pwrite()
- test_blk: clean up, test for edge cases
- virtio_blk: does not support >1 sector per operation, but make it
return -1 rather than asserting so that the new test_blk passes
> Audit ukvm-blk, improve test_blk, plus minor virtio_blk "fix"

- ukvm/ukvm-net.c
The existing tun_alloc() was inherited from older code, it's purpose is
actually to attach to a pre-existing TAP device. Fix the code to behave
as intended.
User-visible change: If uvkm is run without the specified tap device in
existence then it could create a new one with nothing attached to it.
This would hit an obscure assertion as soon as the guest tried to send a
network packet. With these changes we instead attempt to (*) detect this
case and fail immediately with "No such device".
(*) See the code for the gory details, the Linux TUN/TAP API is a
horrible mess so we rely on undocumented but observed behaviour to try
and make this work.
> ukvm: Improve behaviour when attaching TAP device.

- tests/run-tests.sh
- ukvm/ukvm-core.c
User-visible change: "--" now comes before first non-option argument to
ukvm (KERNEL).
Fixes #125.
> ukvm: Fix argument parsing

- ukvm/ukvm-private.h
Commit d0cf32cd5e9d7959c5f66800df1a821b8db68296 introduced the generic
add_overflow() macro for compilers without checked arithmetic builtins.
Unfortunately it also introduced a copy-paste-error for the case where
(b < 1).
This showed up as an "Invalid guest access" in ukvm_port_puts() with a
p->len of 0. This change fixes the typo and the invalid guest access no
longer triggers.
> Fix bug in non-builtin add_overflow() when (b < 1)

- Makefile.common
This has no effect on x86_64 and is a holdover from early cut and paste.
> Remove -mno-3dnow from MD_CFLAGS

- kernel/virtio/mem.c
Consistent with 8bbb81bfb14843a856add84b907ed4bcc9baa876 on the ukvm
side.
> virtio: Remove extra page padding at kernel_end

- ukvm/ukvm-net.c
This allows a more privileged parent process to take care of opening
/dev/net/tun etc and simply pass the open fd to the ukvm child, meaning ukvm
does not now require access to the tun device.
https://github.com/mato/docker-unikernel-runner/pull/4 makes use of this new functionality.
> Optionally accept a pre-existing open tap device fd instead of a name

- kernel/virtio/tscclock.c
- tools/run/solo5-run-virtio.sh
The tscclock code assumed that the RDTSC reading used to compute
time_base at boot time is zero (or close enough). This does not
necessarily hold (see #144 for issues on Bhyve, but can affect QEMU/KVM
and other virtio hypervisors as well).
Correct the computation to
rtc_epochoffset = rtc_boot - time_base
@djwillia, @ricarkol Please review. This only affects virtio targets without `pvclock`.
> tscclock: Correctly compute RTC epoch offset

- Makefile
This is a hangover from the days of when we installed a "ukvm" binary.
> Clean ukvm-configure on solo5-kernel-ukvm uninstall

- CHANGES
- CHANGES.md
- README.md
Now that #153 is in, this PR is the last step before tagging an 0.2.0 release for MirageOS 3.
Changes:
* I've reformatted `CHANGES` as `CHANGES.md` for consistency with other OPAM packages, and added a list of what I think are the most important changes since the initial release, mostly extracted from memory and #82.
* I've removed the majority of the MirageOS-specific instructions in `README.md` and/or replaced them with generic instructions referring to `test_ping_serve`. The main reason for this is that I don't want to duplicate what should go in the MirageOS documentation for the 3.0 release, and I don't want to include information which will be instantly out of date after the release ("use the `mirage-dev` OPAM remote", etc.)
@yomimono, @hannesm What do you think of the 2nd point …
> Documentation updates for 0.2.0 release

- kernel/malloc.c
Clang 3.9 does not parse the default value of USE_LOCKS (0). This
change explicitly sets the value to 0 to appease the compiler. No
functional change intended.
> Explicitly define USE_LOCKS to 0 in dlmalloc

- ukvm/ukvm-core.c
The existing check seems to be incorrect and inconsistent with the comment that precedes it.
> Fix check for KVM 32-bit gap

- kernel/Makefile
- kernel/kernel.h
- kernel/lib.c
- tests/run-tests.sh
- tests/test_blk/test_blk.c
- tests/test_exception/test_exception.c
- tests/test_fpu/test_fpu.c
- tests/test_globals/test_globals.c
- tests/test_hello/test_hello.c
- tests/test_ping_serve/test_ping_serve.c
This change replaces the functions defined in kernel/lib.c with
musl-derived implementations, which are then also used by the tests.
This change is motivated by an immediate need for known-good
implementations of these functions. I had not reviewed the original
implementations until running into major bugs in them today. Eventually
we want a better integration of "nolibc" into both kernel (Solo5) and
application (test) code, so this particular arrangement is temporary.
For simplicity the musl-derived implementations have been stripped down
to use the generic "fallback" implementations where possible.
> Replace kernel/lib.c with musl-derived implementations

- tools/mkimage/solo5-mkimage.sh
Running `solo5-mkimage -f tar blog.tar.gz ./main.native` was failing for me since it can't find `mbr.bin`, `libcom32.c32` and `mboot.c32`. 
Adding the paths for those in this PR creates an image without error. I did encounter another error when uploading the image output Google Compute Engine which may be unrelated:
```
Loading unikernel.bin... ok
Invalid Multiboot image: neither ELF header nor a.out kludge found
boot: 
```
Any idea how to resolve the error above?
> Paths for Syslinux files in Arch Linux

- tools/run/solo5-run-virtio.sh
It seems net-tools is supposed to be phased out and scripts are discouraged from using them. https://lwn.net/Articles/710533/
Only found out about this since I noticed my OS didn't have `ifconfig` by default when I ran `solo5-run-virtio`. Turns out some distros no longer include it by default and expecting people to use iproute2 instead.
> Replace ifconfig with ip command

- tools/run/solo5-run-virtio.sh
PR #169 uses `&>` which is not supported by POSIX shells, replace it
with the usual constructs.
> solo5-virtio-run: Remove bashism

- tests/test_ping_serve/test_ping_serve.c
- ukvm/ukvm_module_net.c
Prior to attaching to a tap device, check that the network inferface is up and running. This gives the user more meaningful feedback regarding this error.
Furthermore, switch to wait-for-packet variant in the ping serve test because ukvm does no longer raise an assertion.
> ukvm_module_net: Check if interface is up and running

- kernel/GNUmakefile
- kernel/cmdline.c
- kernel/ee_printf.c
- kernel/exit.c
- kernel/intr.c
- kernel/kernel.h
- kernel/lib.c
- kernel/log.c
- kernel/ukvm/mem.c
- kernel/virtio/kernel.c
- kernel/virtio/mem.c
- kernel/virtio/pci.c
- kernel/virtio/pvclock.c
- kernel/virtio/tscclock.c
- kernel/virtio/virtio_blk.c
- kernel/virtio/virtio_net.c
- kernel/virtio/virtio_ring.c
- tests/run-tests.sh
- tests/test_quiet/Makefile
- tests/test_quiet/test_quiet.c
Adding two verbosity related args for solo5 unikernels: `--quiet` and `--debug`.
The changes:
- Most current `printf`s were changed to `log(INFO,...)` and `log(WARN,...)`, and the default verbosity level was set to `INFO` (everything that was logged is still logged).
- Parsing and "eating" the --quiet and --debug args is done inside the unikernel at `_start` before calling `solo5_app_main`. To make things simpler, --quiet/--debug args will be understood as --quiet/--debug only if they are the first argument(s) to the unikernel. For example, `${UNIKERNEL} --quiet blabla` and `${UNIKERNEL} --debug --quiet bleble` will run in quiet mode, while `${UNIKERNEL} blabla --quiet` won't. The cmdline argument to the applications for the previous examples would be `blabla`, `bleble` and `blabla …
> Solo5 verbosity

- build.sh
while surf has names of builders, this is not stored in the resulting gist.
> include `uname -a` and `cc --version` output

- ukvm/ukvm_module_net.c
This fixes solo5-net running on FreeBSD (update to #178) with `tap` interfaces which are only up after `open()` was called.
EDIT: this moves the check under the `#ifdef linux` conditional.  It also does not check for the interface being `up` on FreeBSD.
> ukvm_net: move check whether interface is up to after open() on FreeBSD

- tools/run/solo5-run-virtio.sh
Confirmed by trying it and checking the FreeBSD Handbook in 21.7.3
https://www.freebsd.org/doc/handbook/virtualization-host-bhyve.html
> solo5-run-virtio: correct name of freebsd grub2-bhyve package

- kernel/ee_printf.c
gcc 7 warns on switch case fall through.
Due to -Werror this will abort the compilation.
adding /* FALLTHRU */ as a comment stops the warning.
see: https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/
> fix case fall through for gcc 7

- ukvm/ukvm_module_gdb.c
> ukvm gdb: rename --port to --gdb-port, handle strtol errors

- ukvm/ukvm_module_gdb.c
Followup to #208. In this case I actually tested the changes. /cc @hannesm 
Two problems in the original change to --gdb-port:
1. Can't use `strncmp()` to test for `"--gdb"` since this is true for `"--gdb-port=X"` also.
2. `strtol()` error handling is horrible and will happily return `0` with `errno=0` if no digits were matched. Use `sscanf()` instead.
> Fix --gdb-port handling

- ukvm/ukvm_hv_kvm.c
- ukvm/ukvm_hv_kvm_x86_64.c
The two edited files in question call malloc(ukvm_hv_kvm.c) and calloc(ukvm_hv_kvm_x86_64.c), but does not include the standard library. As far as I know, this leads to one of two things; either the compilation aborts because of 'implicit declaration of function'(modern compilers) or the compiler assumes a function that returns an int. The first is safe, while the second can be highly dangerous.
This pull request fixes the problem by including stdlib.h in both files.
> Added missing stdlib.h in ukvm_hv_kvm.c and ukvm_hv_kvm_x86_64.c

- ukvm/ukvm.h
- ukvm/ukvm_cpu_aarch64.c
- ukvm/ukvm_cpu_aarch64.h
- ukvm/ukvm_cpu_x86_64.c
- ukvm/ukvm_cpu_x86_64.h
- ukvm/ukvm_hv_freebsd_x86_64.c
- ukvm/ukvm_hv_kvm_aarch64.c
- ukvm/ukvm_hv_kvm_x86_64.c
- ukvm/ukvm_main.c
I have tested this locally, and (when using MirageOS), values `>=12 MB` are reasonable (with 8 MB the OCaml runtime won't start up, 10 MB results in a out of memory before execution of main in the hello example from mirage-skeleton/tutorial).  Solo5/UKVM uses 2MB steps (see assertion in ukvm_cpu_x86_64: `mem_size & (X86_GUEST_PAGE_SIZE - 1)) == 0` -- where `X86_GUEST_PAGE_SIZE = 2 << 20`), while this `--mem` option allows 1MB granularity.
(It would make more sense to allow for 2MB steps, but it is not very intuitive to do so -- this is why 1MB steps are allowed in this PR, but an odd value results in an assertion failure.)
Previously, each virtual machine mmap()ed 512MB memory (plus overhead in the host system, which seems to be constant 8MB).  With this change, ~50x reduction can be …
> add command line argument for memory size

- README.md
- tests/test_hello/GNUmakefile
Adding a quickstart, and updating the gdb section of the README.
Also, adding the gdb module to tests/test_hello so gdb debugging is easier to play with. It will also be used for the gdb tests to be added after.
> Add quickstart

- build.sh
`x86_64-Debian9-gcc630` now uses the new CI infrastructure, based on
https://github.com/roburio/vm. More nodes will migrate to this in due
course.
> CI: Enable tests on surf nodes that support them

- build.sh
grub-bhyve is a hack, and is unstable under nested virtualization (runs
off into 100% cpu forever). Disable the virtio tests on FreeBSD.
> Disable virtio tests on FreeBSD

- configure.sh
- kernel/malloc.c
since 20180114, FreeBSD-master uses clang 6.0.0.  This introduces new warnings and separated headers further:
- (a) `stdarg.h` now `#include <sys/_stdarg.h>` -- we need `stdarg.h` to define `va_list` (for declaring `vsnprintf`)
- (b) `malloc.c` violates `null-pointer-arithmetic` warnings (see below)
this is not meant to be merged in its current state, instead I'm hoping for directions whether to make the copy for (a) conditional?  and how to proceed with (b)? fix up dlmalloc (the most recent from http://g.oswego.edu/dl/html/malloc.html has the same issues)?  or move it anyways out of solo5 (see #224) and ignore it for now!?
```bash
] gmake
gmake -C kernel ukvm
gmake[1]: Entering directory '/usr/home/hannes/devel/mirage/solo5/kernel'
cc -nostdlibinc -ffreestanding -mno-red-zone -mno-sse …
```
> clang 6.0 on FreeBSD

- kernel/malloc.c
disabling `unknown-pragmas` seems to not work on OpenBSD, as reported by @adamsteen in https://github.com/Solo5/solo5/pull/226/commits/6de9cf7a4fb9c5eb89581ed3ae63d9169ef62623
instead, check for the clang major version being `>= 6`
> malloc: check for clang_major >= 6 to disable null-pointer-arithmetic

- kernel/GNUmakefile
- kernel/muen/muen-block.c
- kernel/muen/muen-console.c
- kernel/muen/muen-net.c
- kernel/muen/muen-yield.c
- kernel/solo5.h
- kernel/ukvm/block.c
- kernel/ukvm/console.c
- kernel/ukvm/kernel.c
- kernel/ukvm/net.c
- kernel/ukvm/yield.c
- kernel/virtio/kernel.c
- kernel/virtio/kernel.h
- kernel/virtio/platform.c
- kernel/virtio/time.c
- kernel/virtio/virtio_blk.c
- kernel/virtio/virtio_net.c
- tests/test_blk/test_blk.c
- tests/test_exception/test_exception.c
- tests/test_fpu/test_fpu.c
- tests/test_globals/test_globals.c
- tests/test_hello/test_hello.c
- tests/test_ping_serve/test_ping_serve.c
- tests/test_quiet/test_quiet.c
- tests/test_time/test_time.c
- ukvm/ukvm_guest.h
- ukvm/ukvm_module_net.c
This is a new take on the Solo5 public API refresh and cleanup (#200, now out of date take 1 in #201).  
Major changes:
- (Tersely) document all public APIs, including their semantics and error handling.
- Remove "type confusion", use the strictest possible types as appropriate throughout.
- Remove use of arch-dependent types where appropriate:
- Introduce solo5_time_t (for time values), solo5_lba_t (for block addressing).
- Standardise on a solo5_result_t for APIs which may return an error at runtime. For all other APIs, explicitly document that the call will either succeed or abort.
- Block I/O changes:
- Rename solo5_blk_read_sync() to solo5_block_read(), solo5_blk_write_sync() to solo5_block_write().
- Introduce a solo5_block_info() call, which replaces the existing _sectors() and …
> Solo5 public API refresh, take 2

- kernel/cpu_aarch64.h
- kernel/cpu_x86_64.h
- kernel/muen/muen-clock.c
- kernel/ukvm/tscclock.c
- kernel/virtio/pvclock.c
- kernel/virtio/tscclock.c
The calculation of tsc_mult will overflow for low values of tsc_freq;
dynamically calculate a suitable tsc_shift where tsc_mult fits into 32
bits.
Additionally, add a DEBUG level log message (visible with --solo5:debug)
to tscclock_init() which prints the values in use on the current
hardware.
TODO: Virtio and muen continue to use a fixed shift of 32 for now,
fixing those targets needs a bit more refactoring to avoid code
duplication.
Thanks to @hannesm for diagnosing the problem and writing the first half
of the fix.
Tested on PCEngines APU2C4 (AMD Embedded G series GX-412TC CPU),
Raspberry Pi 3 model B+ (Broadcom BCM2837B0).
Fixes #242 and also test_time failures observed on ARM64 boards which
have the same root cause.
> ukvm: tscclock: Dynamically calculate tsc_shift

- build.sh
Some CI setups either don't need "sudo" (container based) or will use
"doas" (OpenBSD).
(This PR is also masquerading as a test of the revived `aarch64-Debian9-gcc630` CI, now with end to end tests)
> CI: allow override of "sudo"

- ukvm/ukvm_dumpcore_openbsd_x86_64.c
- ukvm/ukvm_module_dumpcore.c
I tried to compiled solo5 on OpenBSD and ran into trouble, this is the minimal fix I could come up with.
> dumpcore on OpenBSD: provide a stub (copied from ukvm_dumpcore_kvm_aarch64)

- configure.sh
Enable the build or Muen and Virtio on OpenBSD, these complete successfully.
I don't have an easy was of testing the results, sorry.
> Build Muen and Virtio on OpenBSD

- README.md
- docs/architecture.md
- docs/building.md
- docs/debugging.md
- gdb.txt
This is a long overdue re-work of the Solo5 documentation, in preparation for the upcoming 0.3.0 release.
Most of this has already been reviewed out of band by @djwillia and @ricarkol, but am opening a PR for wider review here. Note that this does not need to be 100% complete for the release, especially since parts will change after #172.
@Kensan Could you please supply a link to the Muen-specific instructions I could refer to in `building.md`?
> Documentation re-work for 0.3.0 release

- tests/tests.bats
The tests were not getting run on OpenBSD
9 ukvm tests pass
9 virtio tests fail
1 test not run
`abort ukvm (skipped: not implemented for amd64-unknown-openbsd6.3)`
`18 tests, 9 failures, 1 skipped`
> Ensure tests are run on OpenBSD

- ukvm/ukvm_hv_openbsd_x86_64.c
sync with https://github.com/openbsd/src/commit/02ee787fcd78d11b22dcab625f1f53fd122b6cd9
Successfully built and run mirage-skeleton/tutorial/noop on latest snapshot of OpenBSD amd64-current from this morning, using
$ opam --version
2.0.0~rc3
$ ocaml -version
The OCaml toplevel, version 4.06.0
> vmmvar.h: change vm_exit from union to struct

- docs/building.md
- ukvm/ukvm-configure
With the [cranking of OpenBSD to 6.4](https://marc.info/?l=openbsd-cvs&m=153393283208216&w=2), make this the minimum requirements
> Update OpenBSD requirements to 6.4

- configure.sh
After reading [PIC, PIE and Sanitizers](https://mropert.github.io/2018/02/02/pic_pie_sanitizers/#mixing-up-binaries)
I realized we don't need to try and push -fno-pie every where and complicate all the builds.
remove -fno-pie from CFLAGS
all the solo5 tests run and succeed(for which OpenBSD should pass), i have been able to build and run (resolving failed) http-fetch(mirage-skeleton/device-usage/http-fetch), which previously failed in gmp-freestanding, zarith-freestanding and nocryto(all with hacks to get that far).
> OpenBSD only needs -nopie LDFLAGS, remove -fno-pie from CFLAGS

- .gitignore
- AUTHORS
- GNUmakefile
- Makefile.common
- bindings/GNUmakefile
- bindings/genode/bindings.cc
- bindings/genode/genode_dyn.ld
- bindings/genode/genode_rel.ld
- bindings/genode/stubs.S
- configure.sh
- docs/building.md
- solo5-bindings-genode.opam
- solo5-bindings-genode.pc.in
- solo5-bindings-hvt.opam
- solo5-bindings-muen.opam
- tests/GNUmakefile
- tests/Makefile.tests
- tests/test_abort/GNUmakefile
- tests/test_blk/GNUmakefile
- tests/test_exception/GNUmakefile
- tests/test_fpu/GNUmakefile
- tests/test_globals/GNUmakefile
- tests/test_hello/GNUmakefile
- tests/test_ping_serve/GNUmakefile
- tests/test_quiet/GNUmakefile
- tests/test_time/GNUmakefile
Bindings for linking Solo5 unikernels into Genode native components. The
bindings are provided as a shared library and may be built as a empty
stub library using the host toolchain or the C++ implementation may be
built using the Genode toolchain and build system. Now that there is a
mix of dynamic and static linked Solo5 implementations the "-static"
flag has been removed from the global LDFLAGS and is now explicitly
specified where required.
---
I am able to build the stub library and tests on Linux and FreeBSD, but I did not test building and linking with the whole Mirage stack on FreeBSD. In the near future I will look into creating small boot image for x86_64 that a Solo5 application can be patched into. If this PR clears then I will make a PR at the main Genode repository for a …
> Native Genode bindings

- solo5-bindings-genode.opam
- solo5-bindings-hvt.opam
- solo5-bindings-muen.opam
- solo5-bindings-virtio.opam
- Drop OCaml version dependency entirely (handled by ocaml-freestanding,
nothing compiler-dependent here).
- Normalize 'arch'.
- 'os' availability is based on the build systems we support, standardise
on Linux/FreeBSD/OpenBSD throughout.
- Add existing 'synopsis', 'description' and new ones for Genode.
- Fix 'dev-repo' to use git+https://...
> Migrate to OPAM 2

- tenders/hvt/hvt_freebsd.c
- tenders/hvt/hvt_freebsd.h
chroot to /var/empty
drop to nobody
See #282, #284
> hvt: Basic hvt_drop_privileges on FreeBSD

- bindings/cpu_aarch64.c
- bindings/cpu_aarch64.h
- tenders/hvt/hvt_cpu_aarch64.c
Dumping data abort virtual address is good for debug.
**** Solo5 standalone test_zeropage ****
```Solo5: Trap: EL1 Synchronous Abort caught```
**Data Abort Address: 0x0000000000000008**
```
Solo5: Dump registers:
ESR    : 0x0000000096000047
PC     : 0x0000000000103038
LR     : 0x000000000010302c
PSTATE : 0x00000000800003c5
x00 ~ x03: 0x0000000000000001 0x0000000000000001 0x0000000000000008 0x000000001fffffa8
x04 ~ x07: 0x00000000ffffffff 0x0000000000000000 0x0000000000000001 0x0000000000000001
x08 ~ x11: 0x0000000000105000 0x0000000000000000 0x0000000000000020 0x0000000000104488
x12 ~ x15: 0x000000001ffffc40 0x0000000000105008 0x0000000000000020 0x0000000000000000
x16 ~ x19: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000106000
x20 ~ x23: 0x0000000000010000 …
```
> Dumping data abort address for Arm64

- bindings/cpu_aarch64.c
- tenders/hvt/hvt_cpu_aarch64.c
- panic with "Fatal trap" in CPU trap handler instead of just "PANIC"
(consistent with x86_64, helps tests)
- correctly report if guest memory size is adjusted to more than
requested value
> hvt: arm64: minor fixes

- tenders/hvt/hvt_openbsd.c
Solo5 fails to build on OpenBSD, quick fix changing  `git_t gid` to `gid_t gid`
> fix build, 'git_t gid' should be 'gid_t gid'

- bindings/cpu_aarch64.c
It seems that the log() function doesn't care about the actual
parameter count during parsing the message string.
Signed-off-by: Haibo Xu <haibo.xu@arm.com>
> tenders/hvt: Arm64: Remove redundant parameter in the log message.

- bindings/bindings.h
- bindings/hvt/tscclock.c
- bindings/intr.c
- bindings/mem.c
- bindings/muen/muen-clock.c
- bindings/muen/muen-net.c
- bindings/virtio/tscclock.c
- bindings/virtio/virtio_blk.c
1. Add attribute ((format (printf, 2, 3))) to log() function
to enable printf-style parameter check;
2. Fix some invocations to match the updated definition.
Signed-off-by: Haibo Xu haibo.xu@arm.com
> Enable printf-style parameter check for log() function

- tenders/hvt/hvt_cpu_x86_64.h
This flag "Write Protect (bit 16 of CR0) — When set, inhibits supervisor-level procedures from writing into readonly pages" (From Intel's SW developer manual).
To fix #319
> HVT x86_64: Enable the supervisor write protect flag in cr0

- GNUmakefile
add a `-` to [ -f tenders/hvt/solo5-hvt-debug ], fixed #348
> fix install issue when solo5-hvt-debug is unavailable

- tests/tests.bats
- increase test timeout to 60 seconds as test_ping_serve may take >30s on the test infrastructure.
- increase delay before pinging virtio variant of test_ping_serve as qemu 3.x takes ages to start up.
Fixes #346 and also the OpenBSD test_ping_serve failures (/cc @adamsteen).
> tests: Increase timeout, virtio start delay

- bindings/GNUmakefile
- bindings/bindings.h
- bindings/crt.c
- bindings/crt_init.h
- bindings/genode/bindings.cc
- bindings/genode/stubs.c
- configure.sh
OpenBSD use different symbols for __stack_chk_*
See the following mappings
__stack_chk_guard => __guard_local
__stack_chk_fail => __stack_smash_handler
> SSP for OpenBSD, generic naming of symbols

- tenders/hvt/hvt_openbsd.c
Warn if we are unable to close the vmm file descriptor or ioctl fails to terminate the vm(unikernel), but still exit.
> OpenBSD atexit cleanup - add warnings

- tests/test_dumpcore/GNUmakefile
- tests/test_dumpcore/test_dumpcore.c
- tests/tests.bats
This more accurately reflects what is being tested (the hvt dumpcore
module).
> Rename test_abort to test_dumpcore

- tenders/spt/spt_launch_x86_64.S
- tests/test_fpu/test_fpu.c
Use correct stack alignment on x86_64 in spt_launch. The ABI requires
that (((rsp + 8) % 16) == 0 at entry. This was causing #GP faults in SSE
code.
Modify test_fpu to use aligned variants of SSE instructions, which would
have caught this error.
> spt: Correct stack alignment on x86_64

- bindings/GNUmakefile
- bindings/bindings.h
- bindings/cpu_aarch64.h
- bindings/cpu_x86_64.h
- bindings/crt_init.h
- bindings/genode/bindings.cc
- bindings/genode/stubs.c
- bindings/hvt/platform.c
- bindings/spt/bindings.c
- bindings/spt/bindings.h
- bindings/spt/platform.c
- bindings/spt/start.c
- bindings/spt/sys_linux_x86_64.c
- bindings/tls.c
- bindings/virtio/platform.c
- bindings/virtio/start.c
- include/solo5/solo5.h
- tenders/spt/spt_core.c
- tests/test_tls/GNUmakefile
- tests/test_tls/test_tls.c
- tests/tests.bats
The need for this function was first mentioned in #310.
Some unikernels and language runtimes use thread-local-storage (TLS), like includeos and golang in rumprun. The issue is that these unikernels cannot run on spt because user-level processes do not have enough privileges to set the TLS base registers (%fs in x86_64). To solve this, this PR adds a new `solo5_set_arch_tls_base` function which directly sets the TLS register in virtio/hvt/muen and does an `arch_prctl(SET_FS)` system call in spt (`x86_64`). Setting the `tpidr_el0` register in aarch64 can be done in userspace directly, so no need to call the host, even for spt.
Enabled the `test_notls` test for spt in both `x86_64` and `aarch64`. Tested these changes with this unikernel …
> Add solo5_set_tls_base for thread-local-storage

- tenders/hvt/GNUmakefile
- tenders/hvt/hvt_elf.c
- tenders/hvt/hvt_kvm.c
- tenders/spt/spt_elf.c
- tests/test_wnox/GNUmakefile
- tests/test_wnox/test_wnox.c
- tests/test_xnow/GNUmakefile
- tests/test_xnow/test_xnow.c
- tests/tests.bats
Add tests for W^X, hook up those target/host combinations that are expected to work. Additionally, link solo5-hvt on Linux with `-z noexecstack` and check that sys_personality does not include `READ_IMPLIES_EXEC` at run time (copied from solo5-spt).
> W^X: Add tests, enforce where working

- Makefile.common
- bindings/GNUmakefile
- bindings/hvt/solo5_hvt.lds
- bindings/muen/solo5_muen.lds
- bindings/spt/solo5_spt.lds
- bindings/virtio/solo5_virtio.lds
- configure.sh
Some architectures do not/cannot use 4k pages, so allow for changing the target-specific "guest page size", i.e. the value passed as -z max-page-size to the linker. Update the linker scripts to take this value from the linker rather than hard-coding it.
NOTE: This is a test to see if this approach is portable to the BSDs, specifically if the LLVM linker is happy with `CONSTANT(MAXPAGESIZE)`.
> Allow for differing guest page size

- tests/Makefile.tests
Genode test should link against manifest.genode.o.
> tests: Fix dependencies

- bindings/cpu_x86_64.c
- bindings/cpu_x86_64.h
Until now we were running the (V)CPU slightly out of spec. While this
has not been affecting any current users of Solo5, it was pointed out in
handlers, should someone want to do so.
Fixed by reloading CS, DS, ES, SS in gdt_init() after reloading the GDT.
Fixes #327.
@ricarkol Please double-check this, it seems fine for me.
/cc @Pusnow
> bindings: Reload segment selectors in gdt_init()

- bindings/genode/bindings.cc
- bindings/genode/stubs.c
- bindings/hvt/yield.c
- bindings/spt/net.c
- bindings/virtio/virtio_net.c
- include/solo5/solo5.h
- tests/test_net/test_net.c
Part of #372 / clean-up of #375 :
@hannesm pointed out to me that having `solo5_yield()` return both a `ready_set` and `bool` is redundant, so change the return type to `void`.
@ehmry I've updated the Genode bindings but not tested them.
@ricarkol #377 will need some changes to account for this.
> solo5_yield() should return void

- Makefile.common
- bindings/spt/sys_linux_x86_64.c
- tests/test_wnox/test_wnox.c
- tests/test_xnow/test_xnow.c
Allows us to use C11 features such as _Static_assert.
> Compile with -std=c11 throughout

- bindings/hvt/solo5_hvt.lds
- bindings/muen/solo5_muen.lds
- bindings/spt/solo5_spt.lds
- bindings/virtio/solo5_virtio.lds
- bindings/virtio/start.c
- bindings/virtio/virtio_blk.c
- bindings/virtio/virtio_net.c
- include/solo5/mft_abi.h
- mfttool/mfttool.c
- tenders/common/elf.c
- tenders/common/elf.h
- tenders/common/mft.c
- tenders/common/mft.h
- tenders/hvt/hvt_main.c
- tenders/spt/spt_main.c
The ultimate motivation for this is to allow us to use different ELF notes for different purposes (see https://github.com/Solo5/solo5/issues/372#issuecomment-525272670). This will be useful for ABI versioning. From the commit log:
Make the NOTE loading functionality generic, rather than coupled to loading just a "MFT1" note. elf_load_mft(...) is now renamed as elf_load_note(...). The code is also intentionally decoupled from any dependency on mft_abi.h.
In the process, various NOTE structure alignment issues which were "papered over" in the initial iteration of this code have been fixed now that I have a correct understanding of how (and why) the structures are laid out.
Additional fixes:
- place .note.solo5.manifest in .data (as opposed to .rodata) for virtio and muen, as these bindings …
> ELF loader: Generic NOTE loading

- .travis.yml
- AUTHORS
- bindings/bindings.h
- bindings/cpu_ppc64.h
- bindings/crt_init.h
- bindings/spt/platform.c
- bindings/spt/sys_linux_ppc64le.c
- configure.sh
- tenders/common/elf.c
- tenders/spt/spt_core.c
- tenders/spt/spt_launch_ppc64le.S
- tests/test_fpu/test_fpu.c
- tests/test_seccomp/test_seccomp.c
- tests/test_tls/test_tls.c
This series of patches ports SPT to PowerPC64. We eliminate the access to the thead-local storage's stack_guard by compiling with `-mstack-protector-guard=global`. All libraries and applications have to use the same option and must never use `-fstack-protector-strong` since we do not have a valid TLS.
> Port SPT to PowerPC64 (no TLS access for stack_guard)

- mfttool/mfttool.c
- tenders/common/elf.c
- tenders/common/elf.h
- tenders/hvt/hvt_main.c
- tenders/spt/spt_main.c
Pass an open fd to elf_load_...(), to avoid opening the binary multiple
times. The file name is still passed to allow for descriptive error
reporting. No functional changes.
> ELF loader: Operate on an open fd

- tenders/common/elf.c
- tenders/common/elf.h
- tenders/hvt/hvt.h
- tenders/hvt/hvt_freebsd.c
- tenders/hvt/hvt_kvm.c
- tenders/hvt/hvt_main.c
- tenders/hvt/hvt_openbsd.c
- tenders/spt/spt.h
- tenders/spt/spt_core.c
- tenders/spt/spt_main.c
This allows for tender (spt, hvt) control over how page protection is applied to guest memory. This infrastructure is then used to ensure that guest-executable pages are not also host-executable.
See individual commits for details.
Fixes #390.
/cc @cfcs #370 #303
> Introduce t_guest_mprotect() in ELF loader, fix hvt implementation

- bindings/cpu_ppc64.h
- bindings/spt/sys_linux_ppc64le.c
In case of a syscall error the syscall returns the (positive) errno as
the result and has the summary overflow flag in cr0 set. In our case we
set the result value to -errno (=-r3).
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
> ppc64: Fix syscall interface for syscall error case

- bindings/hvt/solo5_hvt.lds
- bindings/hvt/start.c
- bindings/muen/solo5_muen.lds
- bindings/spt/solo5_spt.lds
- bindings/spt/start.c
- bindings/virtio/bindings.h
- bindings/virtio/solo5_virtio.lds
- bindings/virtio/start.c
- include/solo5/hvt_abi.h
- include/solo5/mft_abi.h
- include/solo5/virtio_abi.h
- tenders/common/elf.h
- tenders/hvt/hvt_main.c
- tenders/spt/spt_main.c
You are wandering around the dark corners of the ELF toolchain. 
You are likely to be eaten by a grue.
As outlined in https://github.com/Solo5/solo5/issues/372#issuecomment-525272670.
----
This change introduces an additional Solo5-owned ELF note, "ABI1", which is used to embed information about the backend target (hvt, spt, ...) and internal tender/bindings ABI version of a unikernel binary linked with the Solo5 bindings.
The internal ABI version is defined as a single uint32_t value, starting at 1. The spt and hvt tenders now refuse to load a binary whose ABI version does not match that of the tender.
----
This is a first draft, and the scheme we are using may yet change. I need to consult with some GCC / LLVM toolchain experts over the next days to be sure that our approach to ELF …
> Implement tender/bindings ABI versioning

- elftool/elftool.c
- elftool/json.h
Improve errors from `solo5-elftool gen-manifest` to include line numbers from the JSON source, for example:
solo5-elftool: _build/manifest.json:4: .devices[...]: name is not alphanumeric
> elftool: Report line number in gen-manifest errors

- bindings/GNUmakefile
- bindings/hvt/solo5_hvt.lds
- bindings/muen/bindings.h
- bindings/muen/muen-block.c
- bindings/muen/muen-clock.c
- bindings/muen/muen-console.c
- bindings/muen/muen-net.c
- bindings/muen/muen-net.h
- bindings/muen/muen-platform_lifecycle.c
- bindings/muen/muen-sinfo.c
- bindings/muen/muen-yield.c
- bindings/muen/solo5_muen.lds
- bindings/muen/start.c
- bindings/muen/util.h
- bindings/muen/writer.c
- bindings/spt/solo5_spt.lds
- bindings/virtio/bindings.h
- bindings/virtio/solo5_virtio.lds
- bindings/virtio/virtio_blk.c
- bindings/virtio/virtio_net.c
- configure.sh
This updates the Muen bindings wrt. the recent API changes and implements multi-device support for network devices (see issue #372). Block devices are still not supported. Only the necessary API changes have been done to the dummy blockdev implementation.
> Implement Multidevice support for Muen

- bindings/muen/muen-platform_lifecycle.c
- bindings/virtio/start.c
- tenders/common/mft.c
- tenders/common/mft.h
As suggested by @cfcs in https://github.com/Solo5/solo5/pull/402#discussion_r325190810. Can't really do much better than this, but at least the internal details of adjusting the size for alignment are encapsulated in a function.
----
Add a mft_get_builtin_mft1() function to extract a struct mft from the MFT1 ELF note. Modify virtio and muen bindings to use it.
> mft: Add mft_get_builtin_mft1()

- bindings/bindings.h
- bindings/hvt/bindings.h
- bindings/hvt/block.c
- bindings/hvt/net.c
- bindings/hvt/platform.c
- bindings/hvt/platform_lifecycle.c
- bindings/hvt/start.c
- bindings/hvt/time.c
- bindings/muen/bindings.h
- bindings/muen/muen-block.c
- bindings/muen/muen-net.c
- bindings/muen/muen-platform_lifecycle.c
- bindings/spt/block.c
- bindings/spt/net.c
- bindings/spt/platform.c
- bindings/virtio/platform.c
- include/solo5/hvt_abi.h
- include/solo5/spt_abi.h
No functional changes.
Inspired by #404, add some more const-ness to (struct mft *) and (struct
mft_entry *) used by the bindings.
For hvt and spt, also make the argument passed to _start() and its
pointer members const, as it is in low memory and will result in a fault
if accidentally modified. The rest is just the ripple-down effect of
these changes.
> bindings: Add some more const-ness for mft, spt/hvt ABI

- include/solo5/solo5.h
Partially addresses #406, see there for details. While I'm at it, clean up some more documentation in solo5.h.
> solo5.h: Document that _acquire_ may only be called once

- GNUmakefile
Genode uses different naming conventions for things... which got lost in the build system refactor.
/cc @ehmry This is not tested in CI and broke my release workflow for 0.6.0 :-(
> Fix OPAM install and uninstall for Genode bindings

- opam/solo5-bindings-genode.opam
- opam/solo5-bindings-hvt.opam
- opam/solo5-bindings-muen.opam
- opam/solo5-bindings-spt.opam
- opam/solo5-bindings-virtio.opam
The CONFIG_ settings passed to "make" must be the same as those passed
to "make opam-install-%", otherwise things will fail.
> OPAM: Fix "make opam-install-%"

- configure.sh
i've got 2.4.1, which should pass >=2.3.3.
> don't warn when libseccomp is new enough

- Makefile.common
Genode bindings were incorrectly passing all of $(CFLAGS) downstream via
$(PC_GENODE_CFLAGS). This was forcing -std=c11 and -Werror on downstream
code, thus causing compilation of e.g. ocaml-freestanding to fail. (See https://github.com/mirage/mirage-solo5/pull/46#issuecomment-533872697)
> genode: Fix OPAM/pkg-config CFLAGS

- build.sh
- tests/e2e-mirage-solo5/README.md
- tests/e2e-mirage-solo5/lib/lib.ml
- tests/e2e-mirage-solo5/unikernel/config.ml
Now that MirageOS and Solo5 are back in sync, re-enable the E2E tests in CI.
> CI: Update and re-enable E2E tests

- configure.sh
- docs/building.md
- tenders/GNUmakefile
Some Linux distributions install libseccomp in non-standard directories.
Use pkg-config to look for it instead of guessing. Note that this
makes pkg-config a hard build-time dependency.
While we're at it, we can use pkg-config to do version tests, so make
libseccomp >= 2.3.3 a hard requirement and warn but proceed on
libseccomp < 2.4.1.
Fixes #419, fixes #418 (by eliminating the no-targets case).
> build: Use pkg-config to find libseccomp on Linux

- scripts/virtio-mkimage/solo5-virtio-mkimage.sh
Fix for #429. The issue is that the latest syslinux broke us; more specifically, the latest mboot.c32 does not default to use the aout kludge option anymore. This commit just adds it with the `-aout` option in the config file.
Tested with `kollerr/solo5-virtio-mkimage`. Just update the script to point to it:
```
--- a/scripts/virtio-mkimage/solo5-virtio-mkimage.sh
+++ b/scripts/virtio-mkimage/solo5-virtio-mkimage.sh
@@ -133,7 +133,7 @@ if [ -n "${RUN_IN_DOCKER}" ]; then
exec docker run --rm \
${TMPFS} \
-v ${SRCDIR}:/host/src -v ${DESTDIR}:/host/dest \
-        mato/solo5-virtio-mkimage -f ${FORMAT} \
+        kollerr/solo5-virtio-mkimage -f ${FORMAT} \
-- \
/host/dest/${DESTFILE} /host/src/${SRCFILE} "$@"
fi
```
and run this:
```
bash ./scripts/virtio-mkimage/solo5-virtio-mkimage.sh -d …
```
> multiboot: add -aout as an argument to mboot.c32

- bindings/muen/muen-net.c
- bindings/muen/solo5_muen.lds
Some small changes to enforce stricter ELF section access rights as well as improvements to muen-net to avoid potential MAC address collisions for unikernels with multiple network interfaces.
> Muen improvements

- .travis.yml
- build.sh
- Travis support for ARM64 is now public, add that.
- PPC64LE is also public, use the production arch: incantations
- Drop _ACTUAL_ARCH, the architecture is now displayed by Travis
- Add descriptive names.
/cc @stefanberger
> Travis: Update, add ARM64

- bindings/hvt/solo5_hvt.lds
- bindings/hvt/start.c
- bindings/muen/solo5_muen.lds
- bindings/muen/start.c
- bindings/spt/solo5_spt.lds
- bindings/spt/start.c
- bindings/virtio/solo5_virtio.lds
- bindings/virtio/start.c
- include/solo5/elf_abi.h
This is implemented for hvt, spt, muen and virtio bindings by:
- Adding a PT_INTERP and .interp in binding-specific linker scripts.
- Populating .interp via DECLARE_ELF_INTERP in binding-specific start.c.
- The content of PT_INTERP is "/nonexistent/solo5/".
The Genode bindings have not been changed, as they seem to do their own
thing regarding PT_INTERP.
With this change if a Solo5 unikernel binary is run directly (e.g.
./test_hello.hvt) on a Linux/FreeBSD/OpenBSD host, the host kernel will
not attempt to execute the binary and will fail with a more or less
sensible error message rather than produce a segmentation fault or
similar.
This provides both for a nicer "naive user" experience, and is a
security improvement against accidentally exposing the host kernel to
unikernel binaries from …
> Stop host kernels from executing Solo5 binaries

- build.sh
- configure.sh
- docs/building.md
Do not implicitly cross-compile Genode bindings for Linux hosts. Do not
assume that the host toolchain can link the tests to the bindings.
Fix #441 
---
I don't have a mainstream Linux installation to test against, so I would prefer to disable cross-compilation. I am still running my own tests of the bindings -  https://opensource.sotest.io/results/41/391
> Disable Genode build for Linux hosts

- bindings/muen/muen-net.c
- bindings/muen/muen-sinfo.c
- bindings/muen/sinfo.h
- bindings/muen/start.c
This pull request updates the subject info implementation to Sinfo 03 and increments the ABI version 2. A check for this new ABI version has been added to Muen with commit [2a64844](https://git.codelabs.ch/?p=muen.git;a=commit;h=2a64844).
It has been manually tested to work with the referenced Muen version, by running `test_hello.muen` on Muen in KVM/QEMU.
> Muen Sinfo & ABI update

- tenders/hvt/hvt_openbsd.c
- tenders/hvt/hvt_openbsd_x86_64.c
This change add support for mprotect_ept ioctl in openbsd, but will only be enabled on an OpenBSD 6.7 system (just gone into beta)
the ifdefs check for VMM_IOC_MPROTECT_EPT, and call if available
Would like to get reviews, so we can add this when 6.7 is released.
> add openbsd mprotect ept support

- build.sh
- tests/tests.bats
PR #447 introduces full W^X support for hvt on OpenBSD 6.7. This followup enables the corresponding tests on OpenBSD 6.7.
As part of this, add some abstractions for declarative skipping of tests and update the call sites to use them where appropriate.
/cc @adamsteen
PR #443 (issue #442) was missing any kind of tests, so add a basic test for this.
> tests.bats: Various improvements

- bindings/muen/muen-platform_lifecycle.c
The MXCSR register is initialized to the default value [1] so there is
no need to explicitly set it.
NOTE: The ABI version is unchanged since there has not been a Solo5 (or
Muen) release since it was raised to 2.
[1] - Muen commit f10bd6b
> muen: Drop explicit FPU initialization

- bindings/hvt/solo5_hvt.lds
- bindings/hvt/start.c
- bindings/muen/solo5_muen.lds
- bindings/muen/start.c
- bindings/spt/solo5_spt.lds
- bindings/spt/start.c
- bindings/virtio/solo5_virtio.lds
- bindings/virtio/start.c
- include/solo5/elf_abi.h
- tests/tests.bats
91a2cce408e75d34a34480e9608b36c28fefa69a introduced the feature of preventing host kernels from executing Solo5 binaries directly, by adding a fake non-existent PT_INTERP.
This change makes it work on OpenBSD by pretending to the host kernel that Solo5 binaries are actually OpenBSD native. See the comments in include/solo5/elf_abi.h for details.
Fixes #442.
> bindings: Prevent OpenBSD from executing Solo5 binaries

- configure.sh
- tenders/GNUmakefile
- tenders/hvt/hvt_freebsd.c
- tenders/hvt/hvt_module_blk.c
- tenders/hvt/hvt_module_dumpcore.c
- tenders/hvt/hvt_module_net.c
- cap_sysctl(3) provides access to the sysctl namespace (restricted
to hw.vmm.destroy)
- hvt_module_dumpcore was changed to use openat(2} and file creation
restricted to the current working directory
- block, net, stdio file descriptors and ioctls have been restricted
as in bhyve(8)
the ppoll(2) capsicum whitelist change was included in the 12-STABLE
branch and will be part of the FreeBSD-12.1 release (scheduled for
Nov 2019)
> capsicum(4) sandbox solo5 on FreeBSD

- configure.sh
The *BSD C runtime header copying code is somewhat fragile and requires
manually keeping track of dependencies of each header that gets copied.
This change uses cc -M to gather a list of dependencies of all the
requested header files, and then cpio to copy the result including
intermediate directories to the target directory.
While I'm at it, remove osreldate.h from SRCS= on FreeBSD, since
as far as I can tell there's nothing that depends on that.
/cc @hannesm @adamsteen
> configure.sh: Improve CRT header copying on BSDs

- configure.sh
This fixes the build for me and i'm able to install solo5-bindings-hvt after this, and build my mirageOS application. Apologies if the upper limit for gcc was set to 9 on purpose, and 10 is not supposed to be supported just yet.
reference: #458
> get configure script to work for gcc > 9

- configure.sh
- opam/solo5-bindings-genode.opam
- opam/solo5-bindings-hvt.opam
- opam/solo5-bindings-muen.opam
- opam/solo5-bindings-spt.opam
- opam/solo5-bindings-virtio.opam
With the release of ocaml-freestanding 0.6.0, we can drop osreldate.h
from the list of system/CRT headers installed on FreeBSD.
Fixes #456.
> configure.sh: Don't install osreldate.h on FreeBSD

- opam/solo5-bindings-genode.opam
- opam/solo5-bindings-hvt.opam
- opam/solo5-bindings-muen.opam
- opam/solo5-bindings-spt.opam
- opam/solo5-bindings-virtio.opam
OPAM 2.x no longer needs a "remove:", and fold Debian and Ubuntu depexts
into "os-family".
Fixes #465.
> OPAM: Update metadata

- bindings/xen/hypercall_page.S
Recent versions of gas emit a warning when the type of a symbol is
changed between incompatible types. DECLARE_HYPERCALL() does this
intentionally, so silence the warning using the method suggested in the
manual [1].
[1] https://sourceware.org/binutils/docs/as/Type.html#Type
> xen: Fix assembler warnings in hypercall_page.S

- tenders/spt/spt_core.c
- tests/tests.bats
libseccomp's seccomp_load() calls free(), which, depending on the libc
malloc() behaviour and generated BPF filter size may call brk(), which
we do not have in our seccomp filter. This leads to a crash during
solo5-spt start-up on some systems.
Work around this by exporting the generated BPF and loading it into the
kernel manually with seccomp().
Fixes #477.
> spt: Load seccomp filter manually

- Makefile.common
This results in e.g.
CC foo.o
rather than
CC foo.c
i.e. show the target being produced rather than the prerequisite(s).
This is consistent with how other build systems do it, and with other
rules in the Makefiles.
> build: Consistently use $@ in silent rules

- bindings/xen/boot.S
- bindings/xen/platform.c
- bindings/xen/solo5_xen.lds
See https://github.com/QubesOS/qubes-issues/issues/6162 for context.
TODO items:
> Xen PVH booting via multiboot protocol (from pvgrub2-pvh)

- tenders/hvt/hvt_kvm_x86_64.c
Minor fix, kvm_cpuid is not used outside of setup_cpuid() so free it when done.
See also #484.
> hvt: kvm: Free kvm_cpuid after use

- bindings/xen/console.c
Left-over from development. Fixes #489.
@talex5 Any objections? This doesn't seem any less performant than what Mini-OS was doing, and just does exactly what the XTF [code](https://xenbits.xen.org/gitweb/?p=xtf.git;a=blob;f=common/console.c;h=b3e89473a7b43266b41b72dff45d7865aa199db9;hb=HEAD#l79) does. It fixes the test unikernel for me, though I can see in real-time that it's pausing for console writes.
> xen: Wait for console backend to process data

- bindings/virtio/virtio_blk.c
- bindings/virtio/virtio_net.c
The configuration functions for virtio blk and net were missing the first step
of the device initialization sequence (virtio spec 1.0).
```
3.1.1 Driver Requirements: Device Initialization
The driver MUST follow this sequence to initialize a device:
1. reset the device.
2. ... <=== we seem to follow everything nicely after this
```
The consequence of this is that a vmm (like QEMU) couldn't boot using a disk
image exposed as a virtio-blk device. This was reported in issue 483.  The
issue is that the boot loader (before solo5 discover the virtio devices)
initializes the device, negotiates features, and reads the kernel from it. The
solo5 kernel then tries to negotiate features again, which is fine, except that
it does it without a reset. This is wrong according to the spec:
```
2.2 Feature …
```
> virtio: add missing reset for net and blk devices

- build.sh
Genode bindings are failing to build on Debian testing / GCC 10.x. Given
that these are going to be removed soon, remove them from CI now so that
we can get it to go green.
> CI: Disable Genode

- bindings/hvt/solo5_hvt.lds
- bindings/muen/solo5_muen.lds
- bindings/spt/solo5_spt.lds
- bindings/virtio/solo5_virtio.lds
- bindings/xen/solo5_xen.lds
- include/solo5/elf_abi.h
Although this syntax is supported by newer versions of GNU ld, it looks it's not supported some older releases. This seems to fix the problem and works for both older and newer versions.
Here's my version of ld, which is still the newer version for Fedora 35 https://src.fedoraproject.org/rpms/binutils
```
GNU ld version 2.37-10.fc35
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
I have tested on the current trunk for GNU binutils and it seems to work tough, which is the same minor version.
```
GNU ld (GNU Binutils) 2.37.50.20211207
Copyright (C) 2021 Free Software Foundation, Inc.
This …
```
> Fix LD scripts syntax

- bindings/solo5_stub.lds
When switching to Fedora 35 and updating to solo5 0.7.0, I've encountered again the error that was fixed by https://github.com/Solo5/solo5/pull/502.
What happened is that in the new stubs ld file introduced in https://github.com/Solo5/solo5/pull/506, the breaking syntax was still used.
> Fix syntax error in stubs ld file

- tests/test_tls/test_tls.c
/cc @hannesm, /cc @TheLortex it's a possible fix for `ppc64` architecture. The fix cast the pointer to `tcb{1,2}._data` to an `uintptr_t` to be able to apply arithmetic operations (`+`) and add the `PPC64_TLS_OFFSET`.
> Fix the compilation of test_tls on ppc64 architecture

- tests/test_zeropage/test_zeropage.c
gcc 12 fails to compile test_zeropage. I have tested this with version 12.1.0 and 12.1.1.
This also breaks the installation via opam on Fedora 36 for me.
```
...
CC test_zeropage.o
test_zeropage.c: In function 'solo5_app_main':
test_zeropage.c:39:5: error: array subscript 0 is outside array bounds of 'uint64_t[0]' {aka 'long unsigned int[]'} [-Werror=array-bounds]
39 |     *addr_invalid = 1;
|     ^~~~~~~~~~~~~
```
There has been some discussion about similar issues on the gcc bug tracker.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578
The best workaround currently seems to be to disable the array bounds diagnostic for cases like this.
> Suppress gcc array bounds warning in test_zeropage

- bindings/xen/platform.c
On recent QubesOS (4.1), this "opaque 'name'" is not present in the multiboot
cmdline.
//cc @xaki23 @palinp @marmarek
> xen: remove the "skip the first token in the cmdline" from multiboot code path

- bindings/xen/platform.c
This unifies the three approaches to memory map:
- multiboot
- start_info
- E820
Since the hypercall and E820 map works in both settings, cut the code complexity
and always use the XENMEM_memory_map.
See https://github.com/QubesOS/qubes-issues/issues/6162 and
https://github.com/mirage/qubes-mirage-firewall/issues/120
> Xen: retrieve mem_size via a hypercall and the E820 map

- README.md
It fixes the broken API documentation link in `README.md`. (I guess it has been broken since [This commit](https://github.com/Solo5/solo5/pull/506/files#diff-9203b578f4415778e29f41c81e1e796621a1c1115bface8840e9c114e89029d6))
> Fix broken API doc link in README.md

- tenders/common/tap_attach.c
The unused-but-set-variable warning was emitted for the variable "up", which is
not used on FreeBSD. To keep the code simple (not introducing further ifdefs),
just ignore it via an empty conditional. Fixes #519.
> tenders, FreeBSD, tap: Ignore "up" variable to avoid compiler warning

- toolchain/cc.in
- toolchain/ld.in
Tools can be called via symlinks, as it is the case in NixOS,
and this leads to these scripts being unable to find include and lib
directories. Calling realpath fixes this.
> Use realpath to determine toolchain paths.

- tenders/common/block_attach.c
Otherwise if the file is not a multiple of block_size (512) we have to make up bytes for the missing part.
> block_attach: check file is aligned

- tenders/common/block_attach.c
- tenders/common/block_attach.h
- tenders/hvt/hvt_module_blk.c
- tenders/spt/spt_module_block.c
- tests/tests.bats
This adds an option to specify a block size different from 512. The block size must be a power of 2 greater than or equal 512.
Marked as a draft as
- it's not well tested,
- I'm not sure about a few details and decisions.
Some things to investigate (CC @Julow):
> Custom block size

- scripts/gen_version_h.sh
When using `git worktree` the file `.git` is a file and not a directory. The file contains a line `gitdir: .../.git/worktrees/...`.
> Fix build when using git worktree

- bindings/cmdline.c
While reading the source code I found that you can pass `--solo5:quiet` to the **guest** to set the log level to **ERROR**. This change adds `--solo5:error` (alias of `--solo5:quiet`), `--solo5:warn` and `--solo5:info`.
Calling `log_set_level(-1)` should silence all log levels *if* it compiles. I can change the semantics of `--solo5:quiet` to that if anyone can confirm whether it is safe to pass `-1`.
> Allow more log levels

- bindings/solo5_hvt.lds
- tenders/hvt/hvt_freebsd.c
- tenders/hvt/hvt_kvm.c
- tenders/hvt/hvt_openbsd.c
- tests/test_rnow/GNUmakefile
- tests/test_rnow/manifest.json
- tests/test_rnow/test_rnow.c
- tests/test_rnox/GNUmakefile
- tests/test_rnox/manifest.json
- tests/test_rnox/test_rnox.c
- tests/test_xnor/GNUmakefile
- tests/test_xnor/manifest.json
- tests/test_xnor/test_xnor.c
- tests/tests.bats
Now for my next trick, execute only Solo5 unikernels?
I wish i could test this, but my hardware is just too old.
Thoughts on taking this forward?
Note: this is dependant on #447 add openbsd mprotect ept support, and would need to be rebased when that went in.
> Make .text execute-only; add tests

- bindings/solo5_hvt.lds
- bindings/solo5_muen.lds
- bindings/solo5_spt.lds
- bindings/solo5_stub.lds
- bindings/solo5_virtio.lds
- bindings/solo5_xen.lds
- configure.sh
- tests/test_tls/test_tls.c
- tests/tests.bats
Hi, this PR should fix the issue of missing thread data section in the linking step (see https://github.com/mirage/ocaml-solo5/pull/124#issuecomment-1380151218). It works (compiles + links) on a 12.2 FreeBSD as well as in my linux fedora AppVM.
I haven't added yet other than spt+hvt, not sure what is needed (maybe xen too to compiles for Xen/Qubes with llvm) and this PR should trigger a CI test to make sure that I haven't broken something.
As a comment it just add a `PT_TLS` section in the ELF binary and the linker is able to merge every TLS bits. The `tbss` part is also now after `bss` to respect the order of the `data` and `tdata` sections but that should not be mandatory.
> fix linker scripts with thread section

- tests/tests.bats
Since some point recently, this test fails (as it is expected to) but with a different error message. This PR adds a case for this.
Alternatively, I propose removing the error message check altogether, since it is too fragile and might be affected - among other things - by locale settings.
> Fix noexec test

- bindings/GNUmakefile
- bindings/muen/time.c
A minimal patch which splits `time.c` between Muen and HVT bindings. Instead to re-use the same code, we copy it to be able to change the Muen clock independantly than HVT.
> Split out C files between muen and hvt bindings

- bindings/solo5_hvt.lds
- bindings/solo5_muen.lds
- bindings/solo5_spt.lds
- bindings/solo5_stub.lds
- bindings/solo5_virtio.lds
- bindings/solo5_xen.lds
With the changes to the linker scripts in #546, the ELF segment containing the bss section is no longer of type PT_LOAD. This means it is not being processed by the Muen script and thus no longer initialized to zero. Explicitly set it to PT_LOAD in the linker script again to restore the original behavior. This was discovered when running Muen test unikernels on hardware, where memory is actually uninitialized and not zeroized as is done on most hypervisors.
Note that the same behavior goes for the common tender ELF loader, see https://github.com/Solo5/solo5/blob/7d5b70f5937abf1e18c2353ffb93d0581ec31a0f/tenders/common/elf.c#L249-L250, thus I believe the same issue is present and the same fix is necessary for the other bindings.
> Fix .bss initialization

- bindings/tls.c
/cc @palainp can you confirm that it's the right fix for `aarch64`?
> Fix the compilation of solo5-aarch64 and the TLS support

- bindings/muen/muen-platform_lifecycle.c
- bindings/muen/start.c
- bindings/solo5_muen.lds
- tests/test_fpu/test_fpu.c
The first two commits make it possible to (re-)use the existing Subject Lifecycle Management of Muen and also apply it to Solo5 unikernels. A possible use case is to configure automatic restarting of unikernels that invoke `solo5_exit()`.
Increasing the ABI version is necessary due to the TLS changes. @dinosaure, maybe you prefer to squash this change into https://github.com/Solo5/solo5/pull/556/commits/806d40ab98595a3f7e6738d8bc29dc036fd111b7, which would be fine by me.
Finally, the adjustment to `test_fpu` has become necessary to successfully run the test on Muen, otherwise a #GP exception is raised. I guess we were lucky with alignment on other x86 bindings. Note that I have only verified that the test works on Muen but CI should show us if it unexpectedly broke `hvt` or any of the …
> Support for Solo5 unikernel lifecycle management on Muen & ABI increase

- CHANGES.md
- include/hvt_abi.h
- include/spt_abi.h
A review will be appreciate when this release include a breaking change.
> Prepare v0.8.0

- bindings/stub/stubs.c
- bindings/tls.c
- include/solo5.h
This prevents a warning when built with -Wstrict-prototypes.
> Fix prototype for solo5_tls_size.

- tenders/hvt/hvt_gdb_x86_64.h
https://github.com/Solo5/solo5/issues/548
Took me a while to get to this, mostly because GDB wire format is weird.
> Fix that GDB HVT bug

- tenders/hvt/hvt_freebsd_x86_64.c
- tenders/hvt/hvt_main.c
- tenders/spt/spt_main.c
The API around VM_RUN changed. With this change, all tests pass. The first commit is to avoid the clang warning:
```
```
I'm still dubious whether shipping releases of solo5 with `-Werror` is a good idea. IMHO it is nice for development, but since C compilers add new warnings in every release, it breaks the software.
FWIW, considering releases -- I'm still using the 0.7 series of solo5, and would appreciate a release in that series if possible. I have a branch (hannesm fork, FreeBSD14-0.7) that includes exactly these two patches, and it would be great to have them merged after review. If you could create a 0.7 branch (off of the v0.7.5 tag), I can open a separate PR.
> support FreeBSD14 in hvt

- tenders/hvt/hvt_cpu_x86_64.c
- tenders/hvt/hvt_cpu_x86_64.h
- tests/tests.bats
The following is a commit done by @mato. I am creating this draft PR to open up for review and hopefully eventually have it merged. I may add comments or changes that I find helpful in understanding the code.
----
Allow for up to 4GB guest size on x86_64 by using up to four PDE entries.
TODO: Lightly tested only, not sure if this arrangement will conflict with any platform memory holes that "plain" KVM may map into guest memory.
> hvt: x86_64: Allow for up to 4GB guest size

- tenders/hvt/hvt_cpu_x86_64.h
- tenders/hvt/hvt_kvm.c
- tenders/hvt/hvt_kvm_x86_64.c
We check the ioctl for `KVM_GET_TSC_KHZ` being -1 only, but according to the documentation it will return `-EIO` (`-5`) when the TSC is unstable (which we check for in errno).  https://www.kernel.org/doc/html/latest/virt/kvm/api.html#kvm-get-tsc-khz
I also updated a reference to Intel SDM which now lives in chapter 24 instead of chapter 23. Maybe we should version the references somehow...
> Check GET_TSC_KHZ return code correctly & update Intel SDM reference

- bindings/spt/net.c
Same fix as in 97a66f6645499fafe77deadbce6d80c73641ea19
Calling solo5_yield(0, ...) results in  passing a struct itimerspec with an it_value of zero in both fields to timerfd_settime(), which disarms the timer, which causes the subsequent call to epoll_pwait() to hang forever if no other file descriptors (external events) have been registered with the waitset.
This addresses https://github.com/mirage/mirage-solo5/issues/97
Dune cache was interfering and this patch only worked once I disabled the dune cache.
> spt: Fix hang in solo5_yield

- tenders/hvt/hvt_module_blk.c
The very same condition and assignment is still present 2 just after the comment
Discovered while looking for the default sector size with @PizieDust
> hvt block: remove redundant check and assignment

- bindings/virtio/platform.c
Dear devs,
To match the code from Xen binding (see commit 5d3a214), if virtio boots via multiboot, do not remove the first token (it is actually an argument).
Best.
> Don't remove the first command line token

- toolchain/gen-headers.sh
This PR adds `stdalign.h` to the set of headers that must be copied over from `/usr/include` on FreeBSD because it is not included in the clang resources on that system. `stdalign.h` is used in OCaml 5.3.0 (discovered in CI for mirage/ocaml-solo5#148).
> Fetch `stdalign.h` from system on FreeBSD

- tenders/hvt/hvt_gdb_kvm_x86_64.c
- tenders/hvt/hvt_gdb_x86_64.h
FPU dumping code written as a part of https://github.com/Solo5/solo5/pull/567.
Needs more thorough tests before merging, but you guys can look at it in the meanwhile.
> Send FPU info to GDB in HVT server.

- tests/test_ssp/test_ssp.c
Recent versions of GCC have -Wstringop-overflow=2 enabled by default, which correctly detects a buffer overflow when we volontary smash the stack during the test. Silence it.
> Silence stringop-overflow warning for SSP test
