kernel/gdt.c, kernel/kernel.c, kernel/lib.c, kernel/time.c, mirage.mk
just formatting
tested with:
```
make config_console
make run
```
=> formatting kernel/*.c files

Makefile, README.md, ukvm/Makefile, ukvm/gdb-stub.c, ukvm/ukvm.c, ukvm/ukvm.h
=> Ukvm mirage gdb

kernel/virtio/time.c
KVM pvclock for monotonic and wall time (Solo5 on KVM/QEMU target).
Timekeeping enhancements #13
=> qemu/kvm solo5 should use pvclocks when available (i.e. kvm)

ukvm/Makefile, ukvm/gdb-stub.c, ukvm/ukvm.c
Cleanup code to compile with -Wall, -Werror.
=> ukvm: Compile with -Wall, -Werror

ukvm/ukvm.c
=> ukvm: Generate random MAC address for guest

Makefile, kernel/Makefile, solo5-kernel-ukvm.pc.in, solo5-kernel-virtio.pc.in
see #50 and #61 -- removes passing through LDLIBS as well...
=> no need for libgcc.a (and any LDLIBS)

kernel/virtio/virtio.c
Dynamically allocate memory for vrings and associated block/net data buffers. This a) reduces memory wastage for network queues which with a queue size of 8192 works out to 12.5MB for each direction and b) moves these structures out of BSS.
=> virtio: Dynamically allocate vrings and data buffers

kernel/Makefile, kernel/abort.c, kernel/ee_printf.c, kernel/interrupts.c, kernel/kernel.h, kernel/malloc.c, kernel/ukvm/low_level.c, kernel/virtio/low_level.c
See individual commits for details. Hopefully nothing controversial here, with the exception of the reduced printf() buffer size.
=> Improved assert() and PANIC()

tests/test_ping_serve/test_ping_serve.c
Reverting the test_ping_serve.c made by mistake on commit c0f519a81c9b5d43cd4afbc301184f9cb9d8c955
=> revert test_ping_serve.c c0f519a8

tests/Makefile, tests/run-tests.sh, tests/test_globals/Makefile, tests/test_globals/test_globals.c, ukvm/ukvm-core.c, ukvm/ukvm-private.h
Fixes #126. See individual commits for details.
@djwillia Please review.
=> ELF loader audit

ukvm/ukvm-core.c
- Fix the edge case mentioned at: https://github.com/Solo5/solo5/pull/127#issuecomment-262622003
- Centralize error handling in load_code()
=> More ELF loader fixes

ukvm/ukvm-configure, ukvm/ukvm-core.c
See individual commits for details. Nothing controversial here.
=> Ukvm cleanups

tools/run/solo5-run-virtio.sh
- Address #141 by using VM<PID> for the bhyve VM name.
- Rather than blowing away an existing bhyve VM of the same name each time we
run, move the cleanup to be done in solo5-run-virtio.sh SIGINT/SIGTERM processing.
=> FreeBSD/bhyve: Use vm<PID> for VM name, VM cleanup change

kernel/cpu.S, kernel/cpu_vectors.S
These two files fell through my `find` recipe for #153, fixing.
=> Fix license headers

tests/run-tests.sh, tests/test_exception/Makefile, tests/test_exception/test_exception.c
Add a simple test to check that guest exceptions are handled by
accessing an out of range address from the guest.
=> tests: Test exception handling

kernel/ukvm/kernel.c, tests/run-tests.sh, tests/test_fpu/Makefile, tests/test_fpu/test_fpu.c, ukvm/ukvm-core.c, ukvm/ukvm-cpu.h
Setup FPU in UKVM monitor instead of guest and add test case for floating point/FPU operation.
=> Ukvm FPU setup & test case

AUTHORS, CHANGES.md
Update `CHANGES.md` and `AUTHORS` for 0.2.2 release.
@gjaldon @Kensan @mdlemay Thank you for your contributions to this release. I have added you as individual contributors to `AUTHORS`, please ping me soonish if you'd like to be listed some other way.
=> Prepare to release 0.2.2

build.sh
See https://github.com/Solo5/solo5-ci. Documentation TBD, this is experimental for now.
=> Add build.sh script for surf-build

configure.sh
The output of 'cc -v' can be localized and is not intended to be
machine-readable. Switch to using 'cc -dM -E' instead. Reject ancient
GCC versions at the same time.
=> Fix compiler detection to not use 'cc -v'

tests/run-tests.sh, tests/test_quiet/test_quiet.c, tools/run/solo5-run-virtio.sh
Fix some bugs introduced by #164 and others discovered in the process of fixing them. Tests now pass again on FreeBSD. See individual commits for details.
/cc @ricarkol
=> Various fixes to self-tests

kernel/solo5.h
This just attempts to document the current "status quo" and known
issues, not trying to fix anything at this point.
=> solo5.h: Add basic documentation for public APIs

ukvm/ukvm_elf.c
Segments can be `PF_R + PF_W + PF_X`. We should not disable writes for those.
Just in case, we only care about `PF_R + PF_X` (executable) segments. And `PR_R`, `PF_W`, and `PF_X` are the only available flags in the header.
=> ukvm_elf: Do not mprotect an elf segment when it's writable.

README.md
...pointing users who want to follow master to Solo5/opam-solo5.
=> README: Add status update

README.md
Add new "Contributing and community" section, with information about the
newly established solo5 mailing list. Remove references to
unikernel.org.
=> Update README (add mailing list)

AUTHORS, GNUmakefile, Makefile.common, configure.sh, solo5-kernel-ukvm.opam, solo5-kernel-ukvm.pc.in, tests/setup-tests.sh, tests/tests.bats, ukvm/ukvm-configure, ukvm/ukvm_gdb_openbsd_x86_64.c, ukvm/ukvm_hv_openbsd.c, ukvm/ukvm_hv_openbsd.h, ukvm/ukvm_hv_openbsd_x86_64.c, ukvm/ukvm_module_gdb.c, ukvm/ukvm_module_net.c
All the changes to get Solo5 working on OpenBSD current.
I have not been able to get "ocaml-freestanding" working yet.
=> Porting ukvm to OpenBSD vmm APIs

CHANGES.md
Update CHANGES.md. I'm sure I've missed some things, but then I don't expect people to read this in detail anyway.
=> Prepare to release 0.3.0

kernel/mem.c
=> Fix array-bounds compile error of solo5-kernel-ukvm

tenders/hvt/cc.h, tenders/hvt/hvt.h, tenders/hvt/hvt_core.c, tenders/hvt/hvt_cpu_x86_64.c, tenders/hvt/hvt_cpu_x86_64.h, tenders/hvt/hvt_elf.c, tenders/hvt/hvt_freebsd.c, tenders/hvt/hvt_gdb.h, tenders/hvt/hvt_gdb_freebsd_x86_64.c, tenders/hvt/hvt_gdb_kvm_x86_64.c, tenders/hvt/hvt_gdb_openbsd_x86_64.c, tenders/hvt/hvt_gdb_x86_64.h, tenders/hvt/hvt_kvm.c, tenders/hvt/hvt_kvm.h, tenders/hvt/hvt_kvm_x86_64.c, tenders/hvt/hvt_main.c, tenders/hvt/hvt_module_blk.c, tenders/hvt/hvt_module_gdb.c, tenders/hvt/hvt_module_net.c, tenders/hvt/hvt_openbsd.c, tenders/hvt/hvt_openbsd_x86_64.c
=> Minor cleanups

docs/building.md
This PR fixes some links to source files in the `docs/building.md`
=> Fix some internal links in in docs/building.md

tenders/spt/spt_core.c
More at #321 
Can add tests and an hvt implementation if needed.
=> spt: Add the --x-exec-heap argument

tenders/common/tap_attach.c
Addressing review comments:
- Check early for (strlen(ifname) >= IFNAMSIZ) and return ENAMETOOLONG
to caller if true.
- Replace strcmp() with strncmp().
- Return errors from strtol() to caller rather than exiting.
- Whitespace.
=> tap_attach: Minor fixes

bindings/hvt/solo5_hvt.lds, bindings/muen/solo5_muen.lds, bindings/spt/solo5_spt.lds, bindings/virtio/solo5_virtio.lds, include/solo5/hvt_abi.h, include/solo5/spt_abi.h, tenders/common/elf.c, tenders/common/elf.h, tenders/common/mft.c, tenders/hvt/hvt_cpu_aarch64.h, tenders/hvt/hvt_cpu_x86_64.h, tenders/hvt/hvt_main.c, tenders/spt/spt_main.c
@cfcs found multiple issues in our ELF loader (#382, #383). This code is quite old and has been in need of review for some time, so here is a first cut of refactoring along with fixes for the reported issues.
See individual commits for details.
Fixes #382, fixes #383, fixes #384.
=> ELF loader: Refactor and fix multiple issues.

bindings/muen/muen-net.c, bindings/muen/muen-platform_lifecycle.c, bindings/virtio/start.c, include/solo5/mft_abi.h, tenders/common/mft.c, tenders/common/mft.h
As suggested by @cfcs in https://github.com/Solo5/solo5/pull/402#discussion_r325192686, and during earlier reviews.
=> manifest: Add extra assertions, enforce const-ness

CHANGES.md, docs/architecture.md, docs/building.md, docs/debugging.md
Documentation updates for the upcoming release. CHANGELOG update coming in a separate commit.
=> Documentation updates for v0.6.0 release

configure.sh
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
=> ppc64: Support ppc64le on RedHat

bindings/genode/bindings.cc
The Genode bindings use a draft version of manifests, this PR brings the bindings up to date.
FWIW I should have CI for testing the latest Solo5 bindings up soon.
=> Genode fixes

build.sh
On Linux/x86_64 Debian VM nodes _only_, test solo5-virtio-mkimage to prevent regressions such as #429. This is not run on Travis, because Ubuntu's syslinux packages are broken.
=> CI: Test solo5-virtio-mkimage

tests/test_tls/test_tls.c, tests/tests.bats
Supersedes #420, mostly with some extra explanation added if someone comes looking later.
=> test_tls: Note (mostly)broken, disable on BSDs

opam/solo5-bindings-genode.pc.in, opam/solo5-bindings-hvt.pc.in, opam/solo5-bindings-muen.pc.in, opam/solo5-bindings-spt.pc.in, opam/solo5-bindings-virtio.pc.in, tests/tests.bats
Add missing `ld` variable to muen pkg-config. Bump version in `.pc` files.
=> Minor fixes

.travis.yml
(Recycling this PR for b733940. Nothing to see here, move along.)
=> CI: Squash Travis warnings

bindings/spt/net.c, tenders/hvt/hvt_core.c, tests/test_time/test_time.c
Fixes #460, plus improvements to test_time.
=> Fix hang in HVT_HYPERCALL_POLL on Linux

tests/tests.bats
Disable until we have a fix for #477.
=> tests: Disable test_mft_maxdevices for spt

bindings/xen/platform.c
Low-level parts required by mirage/mirage#1159 / mirage/mirage#1184 / mirage/mirage-xen#23:
- Obtain E820 memory map via XENMEM_memory_map.
- Provide separate virtual memory range for Mirage/Xen grant mappings.
See individual commits for details.
=> Xen: various improvements

configure.sh, tests/tests.bats
6.7 no longer supported
all support releases use lld
=> Clean Up OpenBSD a bit

CHANGES.md
/cc @hannesm, everything is ok?
=> Update CHANGES for release v0.6.9

RELEASE.md
This is a first shot about a simple explanation of the release process to help anyone to do it.
=> Add a RELEASE.md explanation

CHANGES.md
=> Update CHANGES for release v0.7.0

CHANGES.md
Related to ocaml/opam-repository#20892 (/cc @TheLortex, @hannesm)
=> CHANGES for release v0.7.1

CHANGES.md
If someone has the time for review #515 #516 #517, imho they are well tested (thanks again @palainp @xaki23) and discussed (thx @marmarek) and good to merge and release. This PR adds entries for the changelog.
=> changes for 0.7.2

README.md
(this is a straightforward PR to test the solo5-ci as I'm moving it to a new machine)
=> Update link for mirage.io

tests/test_output/GNUmakefile, tests/test_output/manifest.json, tests/test_output/test_output.c, tests/tests.bats
This is a test case for #537 / #538 for all targets, so we do not end up in any regression.
=> Test over 4k bytes of output (to reproduce #537 #538

configure.sh
fixes [Issue 543](https://github.com/Solo5/solo5/issues/543)
=> On OpenBSD only build for HVT

docs/building.md
=> Add documentation about how to build an unikernel with solo5

scripts/opam-release.sh
//cc @palainp as discussed in #564
=> opam-release: prevent release if there's "-Werror" in Makefile.common

docs/building.md
I got stuck on that for a while, would have give up without the help of Mirage folks around!
I think it is enough to just give the keywords that will allow a reader to investigate further.
=> Docs: add mention of ip forwarding and NAT on host system

opam/solo5-cross-aarch64.opam, opam/solo5.opam
would be great if you could add these to https://github.com/ocaml/opam-repository/pull/27567 as well.
=> add x-maintenance-intent to opam files

configure.sh, tenders/hvt/hvt_openbsd.c, tenders/hvt/hvt_openbsd_x86_64.c
=> Support for hvt on OpenBSD-current
